


#TODO: install:
cp lispeak-settings.py /usr/bin/lispeak-settings  #OR other bin folder, e.g. ~/bin
cp settings.glade /usr/share/lispeak/glade        #OR ~/.local/share/lispeak/glade
cp mic.png /usr/share/lispeak/glade               #OR ~/.local/share/lispeak/glade

